stages:
  - build
  - deploy

build:
  stage: build
  image: docker:26.1.2-cli
  services:
    - docker:26.1.2-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: registry.gitlab.com/hebron-global-llc/hcab-admin-v3/h-cab
    
  before_script:
    - apk add --no-cache apt
    - apk add --update git
    - apk add --no-cache aws-cli
   
    - git --version
    - docker --version
    - aws --version

    # Login to GitLab Container Registry
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

    - export VERSION=$(date +%y.%m.%d.%H)
    - echo $VERSION

  script:
    # Build Docker image for React TypeScript app
    - docker build --no-cache -t h-cab-image:$VERSION .
    - docker tag h-cab-image:$VERSION $IMAGE_NAME:$VERSION
    - docker push $IMAGE_NAME:$VERSION
    - docker rmi h-cab-image:$VERSION
    - echo "Building complete."
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  environment: production
  variables:
    IMAGE_NAME: registry.gitlab.com/hebron-global-llc/hcab-admin-v3/h-cab
  before_script:
    - chmod 400 $SSH_KEY
    - export VERSION=$(date +%y.%m.%d.%H)
    - echo $VERSION
    - echo $IMAGE_NAME
  script:
    - echo "Deploying application..."
    - echo $VERSION
    - echo $IMAGE_NAME

    # Create deployment folder if it does not exist
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$IP_ADDRESS "mkdir -p /home/ubuntu/admin-deployment/"

    # Copy all files from the repository to the server
    - scp -o StrictHostKeyChecking=no -i $SSH_KEY -r . ubuntu@$IP_ADDRESS:/home/ubuntu/admin-deployment/
    
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$IP_ADDRESS "
        echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY &&
        docker stop hcab-admin || true &&
        docker rm hcab-admin || true &&
        docker system prune -a --volumes -f &&
        docker run -d --user root --name hcab-admin -p 3200:3200 --restart=always $IMAGE_NAME:$VERSION"

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
